server:
  port: 9001
  shutdown: graceful

  servlet:
    context-path: /api

spring:
  application:
    name: user-service
  profiles:
    active: local

security:
  oauth2:
    client:
      id: auth_id
      client-secret: auth_secret
    resource:
      jwt:
        key-value: fastview-dev-01-a12zs33zaedfeeaa