spring:
  cloud:
    config:
      #name: config-server
      profile: local
      fail-fast: true
  config:
    import: optional:configserver:http://localhost:8888

#eureka:
#  client:
#    enabled: off
#
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      healthcheck:
        enabled: true
    registry-fetch-interval-seconds: 5 # 서비스 목록 5초마다 캐싱(default : 30초)
    disable-delta: true # 캐싱할 때 변경된 부분만 업데이트(default : false)
    # 유레카 클라이언트 속성 변경 새로고침 비활성화
    refresh:
      enable: false