GET http://localhost:9001/api/v1/cart/usr/6efb1bf8-d3d3-472a-876e-223a2798eb56
Content-Type: application/json


###
POST http://localhost:9001/api/v1/user/shipping-address
Content-Type: application/json
Authorization: Bear

{
  "usrId" : "6efb1bf8-d3d3-472a-876e-223a2798eb56",
  "receiver" : "codeby",
  "phone" : "itemCode",
  "address" : {"postCode" :  "011", "address" : "address", "addressDetail":  "addressDetail"},
  "default" : true
}


###
PATCH http://localhost:9001/api/v1/cart/a7247585-6180-4097-be93-7df16d569dab
Content-Type: application/json

{
  "quantity" : 1
}


###
DELETE http://localhost:9001/api/v1/cart/a7247585-6180-4097-be93-7df16d569dab
Content-Type: application/json


###
